---
title: "Kaggle student grade"
author: "YOON HEO"
date: '2020 2 4 '
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(MASS)
library(ggplot2)
library(corrplot)
library(caret)
library(scales)
library('rpart')
library('randomForest')
library(gridExtra)
select <- dplyr::select
```


### Data

가장 먼저 데이터를 불러온다.

```{r}
## 데이터 로딩
data <- read.csv("student-por.csv")
data2 <- read.csv("student-mat.csv")


## 데이터 바인딩
data$set <- "por"
data2$set <- "mat"
data <- bind_rows(data,data2)
data$set <- as.factor(data$set)


## 데이터 확인
dim(data)
str(data)

data %>%
  select_if(is.numeric) %>%
  summary()

data %>%
  select_if(is.factor) %>%
  summary()

## 데이터 확인 완료

```
  
  

  
## 성적 
### 하향 VS 상향


```{r , fig.align='center', fig.width=9, fig.height=4}

### G1 G2 G3 성적에서 오른기만 한 사람들 VS 떨어지기만 한 사람들
increasing <- data[data$G3 - data$G2 > 0 & data$G2 - data$G1 > 0 , ]
decreasing <- data[data$G3 - data$G2 < 0 & data$G2 - data$G1 < 0 , ]


increasing$setting <- "increasing"
decreasing$setting <- "decreasing"

creasing <- bind_rows(increasing, decreasing)
creasing$setting <- as.factor(creasing$setting)

nrow(increasing)
nrow(decreasing)

summary(increasing)
summary(decreasing)

## school

creasing %>%
  group_by(setting, school) %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(school, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()


## 나이 분포 비교
## 상대적으로 늙은 사람이 성적이 계속 떨어진다.

creasing %>%
  ggplot(aes(age, fill = setting)) +
  geom_density(alpha = 0.5) +
  theme_bw()

## Address 차이 비교
## 도시 살아야 하는 이유가 하나 나왔다.

creasing %>%
  group_by(setting, address) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(address, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## Famsize
## 비슷하다. 동생 때문에 공부 못했단 소리 하지말자.

creasing %>%
  group_by(setting, famsize) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(famsize, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()


## Pstatus
## Pstatus - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)

creasing %>%
  group_by(setting, Pstatus) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(Pstatus, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()


## 엄마 아빠 학력
##Medu - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)
##Fedu - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)

p1 <- creasing %>%
  group_by(setting, Medu) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(Medu, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

p2 <- creasing %>%
  group_by(setting, Fedu) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(Fedu, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

grid.arrange(p1,p2, nrow = 2)


## 엄마 아빠 직업
## Mjob - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')
## Fjob - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')

p1 <- creasing %>%
  group_by(setting, Mjob) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(Mjob, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

p2 <- creasing %>%
  group_by(setting, Fjob) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(Fjob, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

grid.arrange(p1,p2, nrow = 2)

## Reason
## reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')

creasing %>%
  group_by(setting, reason) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(reason, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## guardian
## guardian - student's guardian (nominal: 'mother', 'father' or 'other') 

creasing %>%
  group_by(setting, guardian) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(guardian, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()


## travel Time
## traveltime - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
## 등교 시간도 비슷하다.
## 대체 왜 성적이 떨어진 것일까...?

creasing %>%
  group_by(setting, traveltime) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(traveltime, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()


## studytime
## studytime - weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)

creasing %>%
  group_by(setting, studytime) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(studytime, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## failures
## 실패는 실패일 뿐...

creasing %>%
  group_by(setting, failures) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(failures, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()


## schoolsup

creasing %>%
  group_by(setting, schoolsup) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(schoolsup, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## famsup

creasing %>%
  group_by(setting, famsup) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(famsup, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## paid

creasing %>%
  group_by(setting, paid) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(paid, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## activities

creasing %>%
  group_by(setting, activities) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(activities, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## nursery

creasing %>%
  group_by(setting, nursery) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(nursery, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## higher
## 공부 열정 ㄷㄷ;;;

creasing %>%
  group_by(setting, higher) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(higher, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## internet
## 사실 인터넷이 되냐 안되냐 보다 인터넷으로
## 무엇을 하는지가 더욱 중요하지 않을까 싶다....

creasing %>%
  group_by(setting, internet) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(internet, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## romantic

creasing %>%
  group_by(setting, romantic) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(romantic, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## famrel
## quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
## 가족과의 유대는 지속적인 성적 향상에 영향을 미치는 것 같다

creasing %>%
  group_by(setting, famrel) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(famrel, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## freetime

creasing %>%
  group_by(setting, freetime) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(freetime, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## goout
## goout - going out with friends (numeric: from 1 - very low to 5 - very high)
## 집에만 있는다고 성적이 오르는 것은 아닌가 보다....

creasing %>%
  group_by(setting, goout) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(goout, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

## Dalc & Walc
##Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)<br>
##Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)<br>

p1 <- creasing %>%
  group_by(setting, Dalc) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(Dalc, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

p2 <- creasing %>%
  group_by(setting, Walc) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(Walc, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

grid.arrange(p1,p2, nrow = 2)


## health
## health - current health status (numeric: from 1 - very bad to 5 - very good)<br>
## 성적을 내어주고 건강을 챙긴다.

creasing %>%
  group_by(setting, health) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(health, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()


## absences
## 결석도 안하고 성적도 떨어지는 ???

creasing %>%
  group_by(setting, absences) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n) *100, 1)) %>%
  ggplot(aes(absences, freq, fill = setting)) +
  geom_bar(stat = "identity", position = position_dodge2(0.9)) +
  geom_label(aes(label = paste0(freq , "%")), position = position_dodge2(0.9)) +
  theme_bw()

```


```{r, fig.align='center', fig.width=9, fig.height= 10}

increasing %>%
  select_if(is.numeric) %>%
  cor() %>%
  corrplot(method = "color", type = "upper",
           tl.col = "black",addCoef.col = "black")

decreasing %>%
  select_if(is.numeric) %>%
  cor() %>%
  corrplot(method = "color", type = "upper",
           tl.col = "black",addCoef.col = "black")
```

### 여담 - 결석에 관하여...

결석이 많을수록 성적은 떨어지기 때문에 <br>
G3 시험에서는 결석이 많은 사람이 불리(?)하다. <br>


```{r, warning=FALSE, message=FALSE}
absences_value <- matrix(0, nrow = max(data$absences), ncol = 3)
for(i in 1 : max(data$absences)){
    absences_value[i,] <- data[data$absences > i,c("G1","G2","G3")] %>%
    summarise_all(funs(mean(.))) %>%
    as.matrix()
}

absences_value <- as.data.frame(absences_value, na.rm = T)
absences_value$row <- seq.int(1:nrow(absences_value))

absences_value %>%
ggplot() +
geom_point(mapping = aes(row, V1),col = "red", alpha = 0.5) +
geom_smooth(method = "lm",mapping = aes(row, V1),col = "red", alpha = 0.5,se = FALSE) +
geom_point(mapping = aes(row, V2),col = "blue", alpha = 0.5) +
geom_smooth(method = "lm",mapping = aes(row, V2),col = "blue", alpha = 0.5,se = FALSE) +
geom_point(mapping = aes(row, V3),col = "green", alpha = 0.5) +
geom_smooth(method = "lm",mapping = aes(row, V3),col = "green", alpha = 0.5,se = FALSE) +
theme_bw() +
labs(x = "Row Number", y = "Score")

```

## RF & LG
Random Forest와 Logistic Regrssion으로 
어떤 변수가 중요한지 찾아보자.

```{r}
# data$score <- "noChange"
# data$score[(data$G3 - data$G2 > 0 & data$G2 - data$G1 > 0)] <- "increasing"
# data$score[(data$G3 - data$G2 < 0 & data$G2 - data$G1 < 0)] <- "decreasing"
# data$score <- as.factor(data$score)

colnames(creasing)

### Logistic Regression
glm.fit <- glm(setting ~ age + address + Medu + Fedu + reason + studytime + failures + famrel+ goout + health + absences, data= creasing, family = binomial(link=logit))
summary(glm.fit)

### Random Forest
rf_data <- creasing %>%
  select(age,address, Medu, Fedu, reason, studytime, failures, famrel, goout, health, absences, setting)


rf.1 <- randomForest(x = rf_data[,-12],  y = rf_data[,12],importtance = TRUE, ntree = 1000)
rf.1
varImpPlot(rf.1)


set.seed(1234)
rf_data <- rf_data %>%
  select(-address, -Fedu)
# 
# test_data <- test_data %>%
#   select(-address, -Fedu)

rf.2 <- randomForest(x = rf_data[,-10],  y = rf_data[,10],importtance = TRUE, ntree = 1000)
rf.2
varImpPlot(rf.2)

cv10_1 <- createMultiFolds(rf_data[,10], k = 10, times = 10)
ctrl_1 <- trainControl(method = "repeatedcv", number = 10, repeats = 10, index = cv10_1)
set.seed(3231)
rf.5 <- train(x = rf_data[,-10], y = rf_data[,10], method = "rf", tuneLength = 3, ntree = 1000, trControl = ctrl_1)

print(rf.5)
plot(rf.5)

```

### Conclusion

성적이 떨어지는 여러 가지 요인이 있겠지만 아래의 요소들이 어느정도 차이를 보이고 있다.<br>
큰 차이를 보이는 것도 있고 그렇지 않은 것도 있음.<br>
Logistic Regression과 Random Forest가 중요한 유의미한 값이 다르게 나왔지만<br>
다음의 시각화 + LG + RF를 합쳐보았을 때 다음의 요소가 중요해 보인다.<br><br>

1. 나이 // 애매함<br>
2. 부모님 교육 수준 // 애매함<br>
3. 학교 진학 이유 <br>
4. 수업 실패 경험 <br>
5. 밖에서 친구와 노는 것<br>
6. 결석<br>



<br><br><br><br>


